DROP TABLE IF EXISTS  EYAS_USERS;

CREATE TABLE EYAS_USERS(
  ID INT NOT NULL AUTO_INCREMENT,
  EMAIL VARCHAR(100) NOT NULL,
  ENABLED INT NOT NULL,
  FIRST_NAME VARCHAR(100) NOT NULL,
  LAST_NAME VARCHAR(100) NOT NULL,
  PHONE VARCHAR(100),
  USERNAME VARCHAR(100) NOT NULL,
  PASSWORD VARCHAR(100) NOT NULL,
  PRIMARY KEY ( ID )
);

DROP TABLE IF EXISTS  SCHOOL;
CREATE TABLE SCHOOL(
  ID INT NOT NULL AUTO_INCREMENT,
  TITLE VARCHAR(100) NOT NULL,
  AVERAGE_RATING INT NOT NULL,
  ADDRESS VARCHAR(100) NOT NULL,
  PHONE VARCHAR(100) NOT NULL,
  SNIPPET VARCHAR(100),
  SUB_TITLE VARCHAR(100) NOT NULL,
  SUMMARY VARCHAR(100) NOT NULL,
  PRIMARY KEY ( ID )
);